
" Vundle Plugins part

set nocompatible
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" AutoCompletion
Bundle 'Valloric/YouCompleteMe'

" Syntax Hightlight
Plugin 'scrooloose/syntastic'
Plugin 'nvie/vim-flake8'

" Color Schemes
Plugin 'jnurmine/Zenburn'
Plugin 'altercation/vim-colors-solarized'

" File Browsing
Plugin 'scrooloose/nerdtree'
"
" PowerBar
Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" AutoCompletion Configuration
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

" Syntax highlight

let python_highlight_all=1
syntax on

" hiding useless files from files browsing
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree

" Basic Configs

set encoding=utf-8

" set line numbers
 set nu

" Enable folding
" set foldmethod=indent
" set foldlevel=99

" Indentation for python

au BufNewFile,BufRead *
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

" Flagging unnecessary whitespace

au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/
